/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CapaNegocios;

import CapaDatos.ClienteDAO;
import CapaEntidad.ConstructorCliente;

import java.util.ArrayList;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Gian
 */
public class FrmClientes extends javax.swing.JFrame {
 ClienteDAO oClienteDAO = new ClienteDAO();
  
      public void limpiarClientes(){
      
        txtNombreCliente.setText("");
       txtTelfCliente.setText("");
        txtDniCliente.setText("");
         txtDirecCliente.setText("");
         
         
       
    }
    void activarCajasClientes(boolean v){
       
        txtNombreCliente.setEnabled(v);       
        txtDniCliente.setEnabled(v);
        txtDirecCliente.setEnabled(v);
        txtTelfCliente.setEnabled(v);
        
        
    }
    void activarBotonesClientes(boolean botonAgregar,boolean botonBuscar,boolean botonActualizar,boolean botonEliminar){
        btnAgregarCliente.setEnabled(botonAgregar);
        btnBuscarCliente.setEnabled(botonBuscar);
        btnActualizarCliente.setEnabled(botonActualizar);
        btnEliminarCliente.setEnabled(botonEliminar);   
    }
          
    void listarCliente(){
        DefaultTableModel modelo=new DefaultTableModel();
        String [] titulos= {"Codigo","Nombre","Documento","Direccion","Telfono"};
        modelo.setColumnIdentifiers(titulos);
        ArrayList<ConstructorCliente> lista= oClienteDAO.listarCliente();
        for(ConstructorCliente ocomDatos:lista){
            Object data[]={ocomDatos.getCodigo(),ocomDatos.getNombre(),ocomDatos.getDocumento(),ocomDatos.getDireccion(),ocomDatos.getTelefono()};
            modelo.addRow(data);
        }
        TblClientes.setModel(modelo);
        personalizarTablaCliente();
    
    }
        private void personalizarTablaCliente(){
        TblClientes.getColumnModel().getColumn(0).setPreferredWidth(100);
        TblClientes.getColumnModel().getColumn(1).setPreferredWidth(100);
        TblClientes.getColumnModel().getColumn(2).setPreferredWidth(100);
        TblClientes.getColumnModel().getColumn(3).setPreferredWidth(100);
        TblClientes.getColumnModel().getColumn(4).setPreferredWidth(100);
      
      
     
    }
         void mensaje(String men){
        JOptionPane.showMessageDialog(this, men,"Aviso",1);
    }
         
         public int id_auto(){
         int id_max2 = 1;
       
        
        try{
            id_max2 = oClienteDAO.auto_increm("SELECT MAX(IDCLIENTE) FROM CLIENTE;");
        }catch(Exception ex){
            System.out.println(ex.getMessage());
        }
        return id_max2;
        
    }
         
    public FrmClientes() {
        initComponents();
            this.setLocationRelativeTo(null);
             listarCliente();
             activarCajasClientes(false); 
             activarBotonesClientes(false,true,false,false);
               this.txtIdCliente.setText(String.valueOf(id_auto()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel70 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        btnNuevoCliente = new javax.swing.JButton();
        btnAgregarCliente = new javax.swing.JButton();
        btnActualizarCliente = new javax.swing.JButton();
        btnEliminarCliente = new javax.swing.JButton();
        btnBuscarCliente = new javax.swing.JButton();
        txtIdCliente = new javax.swing.JTextField();
        txtNombreCliente = new javax.swing.JTextField();
        txtDniCliente = new javax.swing.JTextField();
        txtDirecCliente = new javax.swing.JTextField();
        txtTelfCliente = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        TblClientes = new javax.swing.JTable();
        jLabel69 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Clientes");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 0, 51));

        jLabel1.setFont(new java.awt.Font("Javanese Text", 1, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Clientelogo.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Javanese Text", 1, 28)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("CLIENTE");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(578, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE))
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-130, 0, 1010, 80));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Javanese Text", 1, 26)); // NOI18N
        jLabel2.setText("Lista de clientes");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 60, 260, 40));

        jLabel70.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel70.setText("TELF:");
        jPanel2.add(jLabel70, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Direccion:");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel21.setText("DNI:");
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel23.setText("Cliente:");
        jPanel2.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel24.setText("Id Cliente:");
        jPanel2.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        btnNuevoCliente.setBackground(new java.awt.Color(255, 255, 255));
        btnNuevoCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/archivo-nuevo (1).png"))); // NOI18N
        btnNuevoCliente.setText("Nuevo");
        btnNuevoCliente.setBorder(null);
        btnNuevoCliente.setBorderPainted(false);
        btnNuevoCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNuevoCliente.setFocusPainted(false);
        btnNuevoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoClienteActionPerformed(evt);
            }
        });
        jPanel2.add(btnNuevoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 390, 110, 40));

        btnAgregarCliente.setBackground(new java.awt.Color(255, 255, 255));
        btnAgregarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/UserAdd_40960.png"))); // NOI18N
        btnAgregarCliente.setText("Agregar");
        btnAgregarCliente.setBorder(null);
        btnAgregarCliente.setBorderPainted(false);
        btnAgregarCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregarCliente.setFocusPainted(false);
        btnAgregarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarClienteActionPerformed(evt);
            }
        });
        jPanel2.add(btnAgregarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 390, 110, 40));

        btnActualizarCliente.setBackground(new java.awt.Color(255, 255, 255));
        btnActualizarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/UserEdit_40958.png"))); // NOI18N
        btnActualizarCliente.setText("Actualizar");
        btnActualizarCliente.setBorder(null);
        btnActualizarCliente.setBorderPainted(false);
        btnActualizarCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnActualizarCliente.setFocusPainted(false);
        btnActualizarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarClienteActionPerformed(evt);
            }
        });
        jPanel2.add(btnActualizarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 390, 110, 40));

        btnEliminarCliente.setBackground(new java.awt.Color(255, 255, 255));
        btnEliminarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/UserRemove_40959.png"))); // NOI18N
        btnEliminarCliente.setText("Eliminar");
        btnEliminarCliente.setBorder(null);
        btnEliminarCliente.setBorderPainted(false);
        btnEliminarCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminarCliente.setFocusPainted(false);
        btnEliminarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarClienteActionPerformed(evt);
            }
        });
        jPanel2.add(btnEliminarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 390, 110, 40));

        btnBuscarCliente.setBackground(new java.awt.Color(255, 255, 255));
        btnBuscarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buscar (1).png"))); // NOI18N
        btnBuscarCliente.setText("Buscar");
        btnBuscarCliente.setBorder(null);
        btnBuscarCliente.setBorderPainted(false);
        btnBuscarCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscarCliente.setFocusPainted(false);
        btnBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarClienteActionPerformed(evt);
            }
        });
        jPanel2.add(btnBuscarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, 80, 40));

        txtIdCliente.setEnabled(false);
        txtIdCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdClienteActionPerformed(evt);
            }
        });
        txtIdCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIdClienteKeyTyped(evt);
            }
        });
        jPanel2.add(txtIdCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 120, 30));

        txtNombreCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreClienteKeyTyped(evt);
            }
        });
        jPanel2.add(txtNombreCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 190, 30));

        txtDniCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDniClienteKeyTyped(evt);
            }
        });
        jPanel2.add(txtDniCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 190, 30));

        txtDirecCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDirecClienteKeyTyped(evt);
            }
        });
        jPanel2.add(txtDirecCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, 190, 30));

        txtTelfCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelfClienteKeyTyped(evt);
            }
        });
        jPanel2.add(txtTelfCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, 190, 30));

        TblClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(TblClientes);

        jPanel2.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 110, 510, 210));

        jLabel69.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/consumidor.png"))); // NOI18N
        jPanel2.add(jLabel69, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 130, 120));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 880, 430));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 510, 880, 70));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoClienteActionPerformed
      try{
        if(btnNuevoCliente.getText().equalsIgnoreCase("Nuevo")){
            limpiarClientes();
            activarBotonesClientes(true,false,false,false);
            activarCajasClientes(true);
            btnNuevoCliente.setText("Cancelar");
            
            this.txtIdCliente.setText(String.valueOf(id_auto()));
        }else {
            limpiarClientes();
            activarBotonesClientes(false,true,false,false);
            activarCajasClientes(false);
            btnNuevoCliente.setText("Nuevo");
            
        }
        }catch(Exception ex){
           System.out.println("Nuevo : "+ex.getMessage());
      }
    }//GEN-LAST:event_btnNuevoClienteActionPerformed

    private void btnAgregarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarClienteActionPerformed

        try {
            String m=oClienteDAO.agregarCliente(new ConstructorCliente(Integer.parseInt(txtIdCliente.getText()),txtNombreCliente.getText(),Integer.parseInt(txtDniCliente.getText()),txtDirecCliente.getText(),Integer.parseInt(txtTelfCliente.getText())));
            mensaje(m);
            listarCliente();
            limpiarClientes();
            this.txtIdCliente.setText(String.valueOf(id_auto()));
            activarBotonesClientes(false,true,false,false);
            activarCajasClientes(false);
            btnNuevoCliente.setText("Nuevo");
        } catch (Exception ex) {
            System.out.println("Agregar : "+ex.getMessage());
        }

    }//GEN-LAST:event_btnAgregarClienteActionPerformed

    private void btnActualizarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarClienteActionPerformed
      try{
        String m=oClienteDAO.actualizarCliente(new ConstructorCliente(Integer.parseInt(txtIdCliente.getText()),txtNombreCliente.getText(),Integer.parseInt(txtDniCliente.getText()),txtDirecCliente.getText(),Integer.parseInt(txtTelfCliente.getText())));
        mensaje(m);
        listarCliente();
        limpiarClientes();
        this.txtIdCliente.setText(String.valueOf(id_auto()));
        activarBotonesClientes(false,true,false,false);
        activarCajasClientes(false);
        }catch(Exception ex){
           System.out.println("Actualizar : "+ex.getMessage());
      }
    }//GEN-LAST:event_btnActualizarClienteActionPerformed

    private void btnEliminarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarClienteActionPerformed
       try{
           String m=oClienteDAO.eliminarCliente(Integer.parseInt(txtIdCliente.getText()));
       
        mensaje(m);
        listarCliente();
        limpiarClientes();
        this.txtIdCliente.setText(String.valueOf(id_auto()));
        activarBotonesClientes(false,true,false,false);
        activarCajasClientes(false);
        }catch(Exception ex){
           System.out.println("Eliminar : "+ex.getMessage());
      }
    }//GEN-LAST:event_btnEliminarClienteActionPerformed

    private void btnBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarClienteActionPerformed
      
        try{
        ConstructorCliente oCliente;
        int dato=Integer.parseInt(JOptionPane.showInputDialog("Codigo a buscar "));
        oCliente=oClienteDAO.buscarCliente(dato);
        if(oCliente==null){
            mensaje("CODIGO NO EXISTE");
            limpiarClientes();
            activarBotonesClientes(false,false,false,false);
            activarCajasClientes(false);
        }else{
            txtIdCliente.setText(""+oCliente.getCodigo());
            txtNombreCliente.setText(oCliente.getNombre());
            txtDniCliente.setText(""+oCliente.getDocumento());
            txtDirecCliente.setText(oCliente.getDireccion());
            txtTelfCliente.setText(""+oCliente.getTelefono());

            activarBotonesClientes(false,false,true,true);
            activarCajasClientes(true);
        }
        }catch(Exception ex){
           System.out.println("Buscar : "+ex.getMessage());
      }
    }//GEN-LAST:event_btnBuscarClienteActionPerformed

    private void txtDniClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDniClienteKeyTyped
       char validar= evt.getKeyChar();
      if(Character.isLetter(validar)){
          getToolkit().beep();
          evt.consume();
          JOptionPane.showMessageDialog((rootPane), "Ingresar solo Números");
      }
       if(txtDniCliente.getText().length()>=12)
        {
             getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog((rootPane), "Solo se permite 12 digitos");
        }
    }//GEN-LAST:event_txtDniClienteKeyTyped

    private void txtTelfClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelfClienteKeyTyped
      char validar= evt.getKeyChar();
      if(Character.isLetter(validar)){
          getToolkit().beep();
          evt.consume();
          JOptionPane.showMessageDialog((rootPane), "Ingresar solo Números");
      }
       if(txtTelfCliente.getText().length()>=12)
        {
             getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog((rootPane), "Solo se permite 12 digitos");
        }
    }//GEN-LAST:event_txtTelfClienteKeyTyped

    private void txtNombreClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreClienteKeyTyped
          char validar= evt.getKeyChar();
      if(Character.isDigit(validar)){
          getToolkit().beep();
          evt.consume();
          JOptionPane.showMessageDialog((rootPane), "Ingresar solo letras");
      }
         if(txtNombreCliente.getText().length()>=59)
        {
             getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog((rootPane), "Solo se permite hasta 59 caracteres");
        }
    }//GEN-LAST:event_txtNombreClienteKeyTyped

    private void txtIdClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdClienteActionPerformed
       

    }//GEN-LAST:event_txtIdClienteActionPerformed

    private void txtIdClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdClienteKeyTyped
        int key = evt.getKeyChar();
       
       boolean numeros = key >=48 && key <= 57;
        if (!numeros)
        {
             getToolkit().beep();
            evt.consume();
           JOptionPane.showMessageDialog((rootPane), "Ingresar solo Números");
        }
        
        if(txtIdCliente.getText().length()>=4)
        {
            evt.consume();
        }
    }//GEN-LAST:event_txtIdClienteKeyTyped

    private void txtDirecClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDirecClienteKeyTyped
        if(txtDirecCliente.getText().length()>=90)
        {
             getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog((rootPane), "Solo se permite hasta 90 caracteres");
        }
    }//GEN-LAST:event_txtDirecClienteKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmClientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TblClientes;
    private javax.swing.JButton btnActualizarCliente;
    private javax.swing.JButton btnAgregarCliente;
    private javax.swing.JButton btnBuscarCliente;
    private javax.swing.JButton btnEliminarCliente;
    private javax.swing.JButton btnNuevoCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField txtDirecCliente;
    private javax.swing.JTextField txtDniCliente;
    private javax.swing.JTextField txtIdCliente;
    private javax.swing.JTextField txtNombreCliente;
    private javax.swing.JTextField txtTelfCliente;
    // End of variables declaration//GEN-END:variables
}
