/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CapaNegocios;

import CapaDatos.GastosDAO;
import CapaEntidad.ConstructorGastos;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Gian
 */
public class FrmGastos extends javax.swing.JFrame {
    GastosDAO oGastoDAO = new GastosDAO();
void limpiarGastos(){
        
        txtGasto.setText("");
        txtDescripcionGastos.setText("");
        txtMontoGasto.setText(""); 
    }
    void activarCajasGastos(boolean v){
       
        txtGasto.setEnabled(v);
        txtDescripcionGastos.setEnabled(v);
        txtMontoGasto.setEnabled(v);
       
        
        
    }
    void activarBotonesGastos(boolean botonAgregar,boolean botonBuscar,boolean botonActualizar,boolean botonEliminar){
        btnAgregarGasto.setEnabled(botonAgregar);
        btnBuscarGasto.setEnabled(botonBuscar);
        btnActualizarGasto.setEnabled(botonActualizar);
        btnEliminarGasto.setEnabled(botonEliminar);   
    }
    
     void listarGastos(){
          DefaultTableModel modelo=new DefaultTableModel();
        String [] titulos= {"IDGASTO","NOMBRE","DESCRIPCION","MONTO"};
        modelo.setColumnIdentifiers(titulos);
        ArrayList<ConstructorGastos> lista= oGastoDAO.listarGastos();
        for(ConstructorGastos ocomDatos:lista){
            Object data[]={ocomDatos.getCodigo(),ocomDatos.getNombre(),ocomDatos.getDescripcion(),ocomDatos.getMonto()};
            modelo.addRow(data);
        }
        TblGasto.setModel(modelo);
        personalizarTablaGasto();   
    }
      private void personalizarTablaGasto(){
        TblGasto.getColumnModel().getColumn(0).setPreferredWidth(100);
        TblGasto.getColumnModel().getColumn(1).setPreferredWidth(100);
        TblGasto.getColumnModel().getColumn(2).setPreferredWidth(100);
        TblGasto.getColumnModel().getColumn(3).setPreferredWidth(100);
        
    }
      void mensaje(String men){
        JOptionPane.showMessageDialog(this, men,"Aviso",1);
    }
      
      public int id_auto(){
         int id_max2 = 1;
       
        
        try{
            id_max2 = oGastoDAO.auto_increm("SELECT MAX(IDGASTO) FROM GASTOS;");
        }catch(Exception ex){
            System.out.println(ex.getMessage());
        }
        return id_max2;
        
    }
    public FrmGastos() {
        initComponents();
          this.setLocationRelativeTo(null);
        listarGastos();
        activarCajasGastos(false); 
        activarBotonesGastos(false,true,false,false);
          this.txtIdGasto.setText(String.valueOf(id_auto()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnNuevoGasto = new javax.swing.JButton();
        btnAgregarGasto = new javax.swing.JButton();
        btnActualizarGasto = new javax.swing.JButton();
        btnEliminarGasto = new javax.swing.JButton();
        btnBuscarGasto = new javax.swing.JButton();
        txtIdGasto = new javax.swing.JTextField();
        txtGasto = new javax.swing.JTextField();
        txtMontoGasto = new javax.swing.JTextField();
        txtDescripcionGastos = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TblGasto = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gastos");
        setMinimumSize(new java.awt.Dimension(880, 600));
        setPreferredSize(new java.awt.Dimension(880, 600));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 0, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Javanese Text", 1, 32)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Gastos");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 150, 40));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/g.png"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 50));

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Monto:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 130, 60, 20));

        jLabel3.setText("Id Gasto:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        jLabel4.setText("Gasto:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        jLabel5.setText("Descripcion:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 60, -1, -1));

        btnNuevoGasto.setBackground(new java.awt.Color(204, 255, 255));
        btnNuevoGasto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/archivo-nuevo (1).png"))); // NOI18N
        btnNuevoGasto.setText("Nuevo");
        btnNuevoGasto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNuevoGasto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoGastoActionPerformed(evt);
            }
        });
        jPanel2.add(btnNuevoGasto, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, -1, -1));

        btnAgregarGasto.setBackground(new java.awt.Color(204, 255, 255));
        btnAgregarGasto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/gasto.png"))); // NOI18N
        btnAgregarGasto.setText("Agregar");
        btnAgregarGasto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregarGasto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarGastoActionPerformed(evt);
            }
        });
        jPanel2.add(btnAgregarGasto, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, -1, -1));

        btnActualizarGasto.setBackground(new java.awt.Color(204, 255, 255));
        btnActualizarGasto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/editar.png"))); // NOI18N
        btnActualizarGasto.setText("Modificar");
        btnActualizarGasto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnActualizarGasto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarGastoActionPerformed(evt);
            }
        });
        jPanel2.add(btnActualizarGasto, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 220, -1, -1));

        btnEliminarGasto.setBackground(new java.awt.Color(204, 255, 255));
        btnEliminarGasto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/eliminar.png"))); // NOI18N
        btnEliminarGasto.setText("Eliminar");
        btnEliminarGasto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminarGasto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarGastoActionPerformed(evt);
            }
        });
        jPanel2.add(btnEliminarGasto, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 220, -1, -1));

        btnBuscarGasto.setBackground(new java.awt.Color(204, 255, 255));
        btnBuscarGasto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buscar.png"))); // NOI18N
        btnBuscarGasto.setText("Buscar");
        btnBuscarGasto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscarGasto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarGastoActionPerformed(evt);
            }
        });
        jPanel2.add(btnBuscarGasto, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 49, -1, -1));

        txtIdGasto.setEnabled(false);
        jPanel2.add(txtIdGasto, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 51, 70, 30));

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, txtDescripcionGastos, org.jdesktop.beansbinding.ObjectProperty.create(), txtGasto, org.jdesktop.beansbinding.BeanProperty.create("nextFocusableComponent"));
        bindingGroup.addBinding(binding);

        txtGasto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtGastoKeyTyped(evt);
            }
        });
        jPanel2.add(txtGasto, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 121, 160, 30));

        txtMontoGasto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMontoGastoKeyTyped(evt);
            }
        });
        jPanel2.add(txtMontoGasto, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 120, 90, 30));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, txtMontoGasto, org.jdesktop.beansbinding.ObjectProperty.create(), txtDescripcionGastos, org.jdesktop.beansbinding.BeanProperty.create("nextFocusableComponent"));
        bindingGroup.addBinding(binding);

        txtDescripcionGastos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDescripcionGastosKeyTyped(evt);
            }
        });
        jPanel2.add(txtDescripcionGastos, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 55, 200, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 710, 280));

        jLabel6.setBackground(new java.awt.Color(153, 153, 153));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/mano (1).png"))); // NOI18N
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 90, 100));

        jPanel3.setBackground(new java.awt.Color(204, 255, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 280, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 160, 280));

        jPanel4.setBackground(new java.awt.Color(204, 255, 255));

        jLabel7.setFont(new java.awt.Font("Javanese Text", 0, 20)); // NOI18N
        jLabel7.setText("Lista de Gastos");

        TblGasto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TblGasto);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 698, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(101, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(313, 313, 313))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 870, 230));

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarGastoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarGastoActionPerformed
       try{ ConstructorGastos oGastos;
        int dato=Integer.parseInt(JOptionPane.showInputDialog("Codigo a buscar "));
        oGastos=oGastoDAO.buscarGastos(dato);
        if(oGastos==null){
            mensaje("CODIGO NO EXISTE");
            limpiarGastos();
            activarBotonesGastos(false,false,false,false);
            activarCajasGastos(false);
        }else{
            txtIdGasto.setText(""+oGastos.getCodigo());
            txtGasto.setText(oGastos.getNombre());
            txtDescripcionGastos.setText(oGastos.getDescripcion());
            txtMontoGasto.setText(""+oGastos.getMonto());
           

            activarBotonesGastos(false,false,true,true);
            activarCajasGastos(true);
        }
        }catch(Exception ex){
           System.out.println("Buscar : "+ex.getMessage());
      }
    }//GEN-LAST:event_btnBuscarGastoActionPerformed

    private void btnNuevoGastoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoGastoActionPerformed
        try{ if(btnNuevoGasto.getText().equalsIgnoreCase("Nuevo")){
            limpiarGastos();
            activarBotonesGastos(true,false,false,false);
            activarCajasGastos(true);
            btnNuevoGasto.setText("Cancelar");
            this.txtIdGasto.setText(String.valueOf(id_auto()));
        }else {
            limpiarGastos();
            activarBotonesGastos(false,true,false,false);
            activarCajasGastos(false);
            btnNuevoGasto.setText("Nuevo");
           
            
        }}catch(Exception ex){
           System.out.println("Nuevo : "+ex.getMessage());
      }
    }//GEN-LAST:event_btnNuevoGastoActionPerformed

    private void btnAgregarGastoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarGastoActionPerformed
       try {
            String m=oGastoDAO.agregarGastos(new ConstructorGastos(Integer.parseInt(txtIdGasto.getText()),txtGasto.getText(),txtDescripcionGastos.getText(),Float.parseFloat(txtMontoGasto.getText())));
            mensaje(m);
            listarGastos();
            limpiarGastos();
              this.txtIdGasto.setText(String.valueOf(id_auto()));
            activarBotonesGastos(false,true,false,false);
            activarCajasGastos(false);
            btnNuevoGasto.setText("Nuevo");
        } catch (Exception ex) {
            System.out.println("Agregar : "+ex.getMessage());
        }
    }//GEN-LAST:event_btnAgregarGastoActionPerformed

    private void btnActualizarGastoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarGastoActionPerformed
      try{ String m=oGastoDAO.actualizarGastos(new ConstructorGastos(Integer.parseInt(txtIdGasto.getText()),txtGasto.getText(),txtDescripcionGastos.getText(),Float.parseFloat(txtMontoGasto.getText())));
       mensaje(m);
            listarGastos();
            limpiarGastos();
            
              this.txtIdGasto.setText(String.valueOf(id_auto()));
            activarBotonesGastos(false,true,false,false);
            activarCajasGastos(false);
            }catch(Exception ex){
           System.out.println("Actualizar : "+ex.getMessage());
      }
    }//GEN-LAST:event_btnActualizarGastoActionPerformed

    private void btnEliminarGastoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarGastoActionPerformed
        try{
   String m=oGastoDAO.eliminarGastos(Integer.parseInt(txtIdGasto.getText()));
        mensaje(m);
       listarGastos();
            limpiarGastos();
      activarBotonesGastos(false,true,false,false);
            activarCajasGastos(false);
            }catch(Exception ex){
           System.out.println("Eliminar : "+ex.getMessage());
      }
    }//GEN-LAST:event_btnEliminarGastoActionPerformed

    private void txtMontoGastoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMontoGastoKeyTyped
        char validar= evt.getKeyChar();
      if(Character.isLetter(validar)){
          getToolkit().beep();
          evt.consume();
          JOptionPane.showMessageDialog((rootPane), "Ingresar solo Números");
      }
       if(txtMontoGasto.getText().length()>=7)
        {
             getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog((rootPane), "Solo se permite 7 digitos");
        }
      
    }//GEN-LAST:event_txtMontoGastoKeyTyped

    private void txtGastoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtGastoKeyTyped
         char validar= evt.getKeyChar();
      if(Character.isDigit(validar)){
          getToolkit().beep();
          evt.consume();
          JOptionPane.showMessageDialog((rootPane), "Ingresar solo letras");
      }
       if(txtGasto.getText().length()>=70)
        {
             getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog((rootPane), "Solo se permite 70 caracteres");
        }
      
    }//GEN-LAST:event_txtGastoKeyTyped

    private void txtDescripcionGastosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDescripcionGastosKeyTyped
         char validar= evt.getKeyChar();
      if(Character.isDigit(validar)){
          getToolkit().beep();
          evt.consume();
          JOptionPane.showMessageDialog((rootPane), "Ingresar solo letras");
      }
    }//GEN-LAST:event_txtDescripcionGastosKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmGastos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmGastos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmGastos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmGastos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmGastos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TblGasto;
    private javax.swing.JButton btnActualizarGasto;
    private javax.swing.JButton btnAgregarGasto;
    private javax.swing.JButton btnBuscarGasto;
    private javax.swing.JButton btnEliminarGasto;
    private javax.swing.JButton btnNuevoGasto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtDescripcionGastos;
    private javax.swing.JTextField txtGasto;
    private javax.swing.JTextField txtIdGasto;
    private javax.swing.JTextField txtMontoGasto;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
