

package CapaNegocios;

import java.awt.*;
import java.awt.print.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author USER
 */
public class FrmImpresion extends javax.swing.JFrame implements Printable {

       FrmDetalle_Venta DV= new FrmDetalle_Venta();
 private void Imprimir(){
   lblFecha.setText(""+FrmDetalle_Venta.fecha);
   lblCajero.setText(""+FrmDetalle_Venta.cajero);
   lblCliente.setText(""+FrmDetalle_Venta.cliente);
   lblTotal.setText(""+FrmDetalle_Venta.Total);
    
                 
 }
    public FrmImpresion() {
        initComponents();
          Imprimir();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Impre = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lblCliente = new javax.swing.JLabel();
        lblCajero = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblVenta = new javax.swing.JTable();
        jSeparator11 = new javax.swing.JSeparator();
        btnImprimir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        Impre.setLayout(null);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/planeta-tierra.png"))); // NOI18N
        jLabel17.setText("B&A");
        Impre.add(jLabel17);
        jLabel17.setBounds(0, 10, 420, 40);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Centro de acopio de reciclaje  \"B&A\"");
        Impre.add(jLabel2);
        jLabel2.setBounds(0, 70, 420, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("RUC:10742297681");
        Impre.add(jLabel4);
        jLabel4.setBounds(0, 90, 420, 20);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("VIRGEN DEL CARMEN II Mz.C LT.5");
        Impre.add(jLabel5);
        jLabel5.setBounds(0, 133, 420, 20);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("CARABAYLLO, CARMEN TORRE BLANCA");
        Impre.add(jLabel6);
        jLabel6.setBounds(0, 150, 420, 20);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("BOLETA ELECTRÓNICA");
        Impre.add(jLabel8);
        jLabel8.setBounds(0, 180, 420, 15);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("FECHA:");
        Impre.add(jLabel9);
        jLabel9.setBounds(10, 200, 50, 14);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setText("CAJERO:");
        Impre.add(jLabel12);
        jLabel12.setBounds(10, 230, 60, 14);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("CLIENTE:");
        Impre.add(jLabel11);
        jLabel11.setBounds(10, 260, 60, 14);

        lblCliente.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblCliente.setText("----");
        Impre.add(lblCliente);
        lblCliente.setBounds(80, 255, 120, 20);

        lblCajero.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblCajero.setText("----");
        Impre.add(lblCajero);
        lblCajero.setBounds(80, 225, 120, 20);

        lblFecha.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblFecha.setText("----");
        Impre.add(lblFecha);
        lblFecha.setBounds(80, 195, 110, 20);

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel23.setText("TOTAL PAGAR:");
        Impre.add(jLabel23);
        jLabel23.setBounds(260, 580, 81, 30);

        lblTotal.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblTotal.setText("----");
        Impre.add(lblTotal);
        lblTotal.setBounds(350, 580, 60, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("REDUCE    REUTILIZA    RECICLA");
        Impre.add(jLabel7);
        jLabel7.setBounds(0, 640, 420, 14);

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Cel: 963020726-902822015");
        Impre.add(jLabel18);
        jLabel18.setBounds(0, 110, 420, 20);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("¡GRACIAS POR SU VENTA!");
        Impre.add(jLabel10);
        jLabel10.setBounds(0, 620, 420, 14);

        jSeparator7.setForeground(new java.awt.Color(0, 0, 0));
        Impre.add(jSeparator7);
        jSeparator7.setBounds(0, 70, 420, 10);

        jSeparator8.setForeground(new java.awt.Color(0, 0, 0));
        Impre.add(jSeparator8);
        jSeparator8.setBounds(0, 172, 420, 0);

        jSeparator9.setForeground(new java.awt.Color(0, 0, 0));
        Impre.add(jSeparator9);
        jSeparator9.setBounds(0, 130, 420, 10);

        jSeparator10.setForeground(new java.awt.Color(0, 0, 0));
        Impre.add(jSeparator10);
        jSeparator10.setBounds(0, 610, 430, 10);

        tblVenta.setBackground(new java.awt.Color(240, 240, 240));
        tblVenta.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        tblVenta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PESO KG", "PROD", "PRECIO", "TOTAL"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblVenta.setEnabled(false);
        tblVenta.setFocusable(false);
        tblVenta.setGridColor(new java.awt.Color(255, 255, 255));
        tblVenta.setOpaque(false);
        tblVenta.setSelectionBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(tblVenta);
        if (tblVenta.getColumnModel().getColumnCount() > 0) {
            tblVenta.getColumnModel().getColumn(0).setMaxWidth(100);
            tblVenta.getColumnModel().getColumn(1).setMaxWidth(120);
            tblVenta.getColumnModel().getColumn(2).setMaxWidth(100);
            tblVenta.getColumnModel().getColumn(3).setMaxWidth(100);
        }

        Impre.add(jScrollPane1);
        jScrollPane1.setBounds(0, 280, 420, 300);

        jSeparator11.setForeground(new java.awt.Color(0, 0, 0));
        Impre.add(jSeparator11);
        jSeparator11.setBounds(0, 580, 420, 10);

        btnImprimir.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnImprimir.setText("Imprimir");
        btnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Impre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addComponent(btnImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(135, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Impre, javax.swing.GroupLayout.DEFAULT_SIZE, 657, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnImprimir))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirActionPerformed
        
        try{
               PrinterJob job= PrinterJob.getPrinterJob();
               job.setPrintable(this);
               boolean top = job.printDialog();
               if(top)
               {
                 job.print();
               }
         
       
        }catch(PrinterException e){
            JOptionPane.showMessageDialog(this,"La impresion se cancelo"+ e.getMessage());
        }

    }//GEN-LAST:event_btnImprimirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmImpresion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmImpresion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmImpresion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmImpresion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new FrmImpresion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Impre;
    private javax.swing.JButton btnImprimir;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JLabel lblCajero;
    private javax.swing.JLabel lblCliente;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblTotal;
    public static javax.swing.JTable tblVenta;
    // End of variables declaration//GEN-END:variables

    @Override
    public int print(Graphics graf, PageFormat pagfor, int index) throws PrinterException {
       
        if(index>0){
            return NO_SUCH_PAGE;
        }else{
        
            Graphics2D hub = (Graphics2D)graf;
            hub.translate(pagfor.getImageableX()+30,pagfor.getImageableY()+30);
            hub.scale(1.0,1.0);
            Impre.printAll(graf);
            return PAGE_EXISTS;
    }
    
}
}
