 /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CapaNegocios;

//NUEVO
import Conexion.ConexionSQL;
import com.sun.glass.events.KeyEvent;
import java.awt.Color;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class FrmLogin extends javax.swing.JFrame {

    public static String usuarios="";
    ConexionSQL oconexion = new ConexionSQL();
     Connection cn=oconexion.abrirConexion();
    

    /**
     * Creates new form FrmLogin
     */
    
    public FrmLogin() {
        initComponents();
        this.setLocationRelativeTo(this);
        txtUsu.requestFocus();
    }
     public void IngresarAdministrador()
    {
        if(txtContra.getText().isEmpty()&&txtUsu.getText().isEmpty()){
            txtContra.setForeground(Color.red);
            txtUsu.setForeground(Color.red);
             txtUsu.setText("Ingresar usuario");
             txtContra.setText("Ingresar contraseña");
             txtAlertar.setBackground(Color.red);
              
        }else if(txtUsu.getText().isEmpty()){
        
                 txtUsu.setForeground(Color.red);
                 txtUsu.setText("Ingresar usuario");
                
                 txtAlertar.setBackground(Color.red);
                
                
        }else if(txtContra.getText().isEmpty()){
            txtContra.setForeground(Color.red);
             txtContra.setText("Ingresar contraseña");
            
                txtAlertar.setBackground(Color.red);
        }
        
        else if(txtUsu.getText().equals("administrador")&&txtContra.getText().equals("123456"))
        { 
        try{ 
            usuarios=txtUsu.getText();
                 FrmMenuPrincipal lg = new FrmMenuPrincipal();
                 lg.setVisible(true);
                 lg.setLocationRelativeTo(null);
                 this.dispose();
                
            
        }catch(Exception e){  
                 JOptionPane.showMessageDialog(this,e.toString(),"Aviso",1);
            }
        }else
        {
                txtUsu.setForeground(Color.red);
                txtContra.setForeground(Color.red);
                 txtAlertar.setBackground(Color.red);
               
               
        }
    }
     
     public void IngresarUsuario(){
        int resultado=0;
          String pass=String.valueOf(txtContra.getPassword());
        String usuario=txtUsu.getText();
     
               if(txtContra.getText().isEmpty()&&txtUsu.getText().isEmpty()){
            txtContra.setForeground(Color.red);
            txtUsu.setForeground(Color.red);
             txtUsu.setText("Ingresar usuario");
             txtContra.setText("Ingresar contraseña");
             txtAlertar.setBackground(Color.red);
              
        }else if(txtUsu.getText().isEmpty()){
        
                 txtUsu.setForeground(Color.red);
                 txtUsu.setText("Ingresar usuario");  
                 txtAlertar.setBackground(Color.red);
                
                
        }else if(txtContra.getText().isEmpty()){
            txtContra.setForeground(Color.red);
             txtContra.setText("Ingresar contraseña");            
             txtAlertar.setBackground(Color.red);
             
             
        }else{
            
          
          String SQL="select * from USUARIO where NOMBREUSUARIO='"+usuario+"' and CONTRASEÑA ='"+pass+"'  ";
       
        try {
            Statement st=cn.createStatement();
            ResultSet rs=st.executeQuery(SQL) ;
            
            if (rs.next()) {
                resultado=1;
                if(resultado==1) {
                    usuarios=txtUsu.getText();
                    FrmMenuPrincipal form= new FrmMenuPrincipal();
                    form.setVisible(true);
                    form.setLocationRelativeTo(null);
                    this.dispose();
                    
                }
                
        
        }}catch(Exception e){
            
            txtUsu.setForeground(Color.red);
            txtContra.setForeground(Color.red);
            txtAlertar.setBackground(Color.red);
        }
     }}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtUsu = new javax.swing.JTextField();
        txtContra = new javax.swing.JPasswordField();
        txtAlertar = new javax.swing.JLabel();
        txtIniciar = new javax.swing.JLabel();
        lblCerrar = new javax.swing.JLabel();
        lblMinimizar = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        lblKey = new javax.swing.JLabel();
        lblVer = new javax.swing.JLabel();
        lblImagen = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(13, 29, 92));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("¡BIENVENIDO!");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 321, -1));

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 3, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("HYV PROGRAMS ");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, -1, 23));

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 3, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("esta aplicación");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 380, -1, 23));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel8.setBackground(new java.awt.Color(153, 153, 153));
        jLabel8.setOpaque(true);

        jLabel9.setBackground(new java.awt.Color(153, 153, 153));
        jLabel9.setEnabled(false);
        jLabel9.setOpaque(true);

        txtUsu.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtUsu.setForeground(new java.awt.Color(153, 153, 153));
        txtUsu.setBorder(null);
        txtUsu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtUsuMouseClicked(evt);
            }
        });

        txtContra.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtContra.setForeground(new java.awt.Color(153, 153, 153));
        txtContra.setToolTipText("");
        txtContra.setBorder(null);
        txtContra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtContraMouseClicked(evt);
            }
        });
        txtContra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtContraKeyPressed(evt);
            }
        });

        txtAlertar.setBackground(new java.awt.Color(255, 255, 255));
        txtAlertar.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        txtAlertar.setForeground(new java.awt.Color(255, 255, 255));
        txtAlertar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtAlertar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/error_1.png"))); // NOI18N
        txtAlertar.setText("Error al iniciar sesión");
        txtAlertar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtAlertar.setOpaque(true);
        txtAlertar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtAlertarMouseClicked(evt);
            }
        });

        txtIniciar.setBackground(new java.awt.Color(13, 29, 92));
        txtIniciar.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        txtIniciar.setForeground(new java.awt.Color(255, 255, 255));
        txtIniciar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtIniciar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnContinuar.png"))); // NOI18N
        txtIniciar.setText("Iniciar sesión");
        txtIniciar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtIniciar.setOpaque(true);
        txtIniciar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtIniciarMouseClicked(evt);
            }
        });

        lblCerrar.setBackground(new java.awt.Color(13, 29, 92));
        lblCerrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn-cerrar.png"))); // NOI18N
        lblCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCerrar.setOpaque(true);
        lblCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCerrarMouseClicked(evt);
            }
        });

        lblMinimizar.setBackground(new java.awt.Color(13, 29, 92));
        lblMinimizar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn-minimizar.png"))); // NOI18N
        lblMinimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblMinimizar.setOpaque(true);
        lblMinimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMinimizarMouseClicked(evt);
            }
        });

        lblUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/label-usuario.png"))); // NOI18N

        lblKey.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblKey.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/label-contraseña.png"))); // NOI18N

        lblVer.setBackground(new java.awt.Color(13, 29, 92));
        lblVer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblVer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnVista.png"))); // NOI18N
        lblVer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblVer.setOpaque(true);
        lblVer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblVerMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblVerMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblMinimizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCerrar))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lblUsuario)
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtUsu)
                        .addComponent(txtIniciar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtAlertar, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                        .addComponent(lblKey)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(txtContra, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lblVer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMinimizar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addComponent(lblUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblKey)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblVer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtContra, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(txtIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtAlertar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(349, 0, -1, 419));

        lblImagen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/MarcaPersonal.jpg"))); // NOI18N
        jPanel1.add(lblImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 316, -1));

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 3, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Por favor inicia sesión para poder utilizar");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, -1, 23));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtAlertarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAlertarMouseClicked
        txtContra.setText("");
        txtUsu.setText("");
        txtUsu.requestFocus();
        txtUsu.setForeground(new Color(153,153,153));
        txtContra.setForeground(new Color(153,153,153));
          txtAlertar.setBackground(Color.white);
       
    }//GEN-LAST:event_txtAlertarMouseClicked

    private void txtIniciarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtIniciarMouseClicked
       try{ IngresarAdministrador();
        IngresarUsuario();
        }catch(Exception ex){
           System.out.println("Iniciar : "+ex.getMessage());
      }
    }//GEN-LAST:event_txtIniciarMouseClicked

    private void txtContraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtContraMouseClicked
        lblVer.setBackground(new Color(13,29,92));	
    }//GEN-LAST:event_txtContraMouseClicked

    private void lblCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrarMouseClicked
       try{ System.exit(0);}catch(Exception ex){
           System.out.println("Cerrar : "+ex.getMessage());
      }
    }//GEN-LAST:event_lblCerrarMouseClicked

    private void lblMinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizarMouseClicked
      this.setExtendedState(1);
    }//GEN-LAST:event_lblMinimizarMouseClicked

    private void txtUsuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUsuMouseClicked
          lblVer.setBackground(Color.white);
    }//GEN-LAST:event_txtUsuMouseClicked

    private void lblVerMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVerMouseReleased
         txtContra.setEchoChar('•');
    }//GEN-LAST:event_lblVerMouseReleased

    private void lblVerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVerMousePressed
          txtContra.setEchoChar((char)0);
    }//GEN-LAST:event_lblVerMousePressed

    private void txtContraKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtContraKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
         IngresarAdministrador();
        IngresarUsuario();
       }
    }//GEN-LAST:event_txtContraKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblCerrar;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JLabel lblKey;
    private javax.swing.JLabel lblMinimizar;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JLabel lblVer;
    private javax.swing.JLabel txtAlertar;
    private javax.swing.JPasswordField txtContra;
    private javax.swing.JLabel txtIniciar;
    private javax.swing.JTextField txtUsu;
    // End of variables declaration//GEN-END:variables
}
