    /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CapaNegocios;

import java.awt.Color;
import javax.swing.JOptionPane;

//NUEVO

/**
 *
 * @author Gian
 */
public class FrmMenuPrincipal extends javax.swing.JFrame {
FrmLogin ventana= new FrmLogin();

    void Restriccion(){
        try{ 

         if(txtUsu.getText().equals("Usuario Activo: administrador"))
        { 
            activarPaneles(true, true, true, true);
        }else
        {
               
           activarPaneles(false, false, false, false);
               
        }
        }catch(Exception e){  
                 JOptionPane.showMessageDialog(this,e.toString(),"Aviso",1);
            }
    }

    void activarPaneles(boolean Caja,boolean Gastos,boolean Personal,boolean Usuario){
        lblCaja.setVisible(Caja);
        lblGastos.setVisible(Gastos);
        lblPersonal.setVisible(Personal);
        lblusuarios.setVisible(Usuario); 
        tabCaja.setVisible(Caja);
        tabGastos.setVisible(Gastos);
        tabPersonal.setVisible(Personal);
        tabUsuarios.setVisible(Usuario);
    }
   
    
    
    
    public FrmMenuPrincipal() {
        initComponents();   
        this.setExtendedState(6);
         
        txtUsu.setText("Usuario Activo: "+ventana.usuarios);
       
         Restriccion();
         
         
         

    }
    
   
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        tabhome = new javax.swing.JPanel();
        lblHome = new javax.swing.JLabel();
        tabPersonal = new javax.swing.JPanel();
        lblPersonal = new javax.swing.JLabel();
        tabCaja = new javax.swing.JPanel();
        lblCaja = new javax.swing.JLabel();
        tabVenta = new javax.swing.JPanel();
        lblVentas = new javax.swing.JLabel();
        tabGastos = new javax.swing.JPanel();
        lblGastos = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        tabUsuarios = new javax.swing.JPanel();
        lblusuarios = new javax.swing.JLabel();
        tabCliente1 = new javax.swing.JPanel();
        lblClientes = new javax.swing.JLabel();
        tabInventario = new javax.swing.JPanel();
        lblInventarios = new javax.swing.JLabel();
        tabProductos = new javax.swing.JPanel();
        lblProductos = new javax.swing.JLabel();
        tabBoleta = new javax.swing.JPanel();
        lblBoleta = new javax.swing.JLabel();
        txtUsu = new javax.swing.JLabel();
        txtCerrarSesion = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        panelhome = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        tabhome.setBackground(new java.awt.Color(204, 255, 204));
        tabhome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabhomeMouseClicked(evt);
            }
        });

        lblHome.setBackground(new java.awt.Color(204, 204, 255));
        lblHome.setFont(new java.awt.Font("Lato", 1, 18)); // NOI18N
        lblHome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/home.png"))); // NOI18N
        lblHome.setText("Home");
        lblHome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHomeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout tabhomeLayout = new javax.swing.GroupLayout(tabhome);
        tabhome.setLayout(tabhomeLayout);
        tabhomeLayout.setHorizontalGroup(
            tabhomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        tabhomeLayout.setVerticalGroup(
            tabhomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabhomeLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblHome, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        tabPersonal.setBackground(new java.awt.Color(204, 255, 204));

        lblPersonal.setFont(new java.awt.Font("Lato", 1, 18)); // NOI18N
        lblPersonal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPersonal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/3592856-general-group-office-personal-relation-team-team-structure_107770.png"))); // NOI18N
        lblPersonal.setText("Personal");
        lblPersonal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblPersonal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPersonalMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout tabPersonalLayout = new javax.swing.GroupLayout(tabPersonal);
        tabPersonal.setLayout(tabPersonalLayout);
        tabPersonalLayout.setHorizontalGroup(
            tabPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblPersonal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        tabPersonalLayout.setVerticalGroup(
            tabPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblPersonal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
        );

        tabCaja.setBackground(new java.awt.Color(204, 255, 204));
        tabCaja.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tabCaja.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabCajaMouseClicked(evt);
            }
        });

        lblCaja.setFont(new java.awt.Font("Lato", 1, 18)); // NOI18N
        lblCaja.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCaja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cashier_icon-icons.com_53629.png"))); // NOI18N
        lblCaja.setText("   Caja");
        lblCaja.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCaja.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCajaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout tabCajaLayout = new javax.swing.GroupLayout(tabCaja);
        tabCaja.setLayout(tabCajaLayout);
        tabCajaLayout.setHorizontalGroup(
            tabCajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabCajaLayout.createSequentialGroup()
                .addComponent(lblCaja, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        tabCajaLayout.setVerticalGroup(
            tabCajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblCaja, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
        );

        tabVenta.setBackground(new java.awt.Color(204, 255, 204));
        tabVenta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lblVentas.setFont(new java.awt.Font("Lato", 1, 18)); // NOI18N
        lblVentas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconfinder-basket-4341280_120547 (1).png"))); // NOI18N
        lblVentas.setText("Ventas");
        lblVentas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblVentas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblVentasMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout tabVentaLayout = new javax.swing.GroupLayout(tabVenta);
        tabVenta.setLayout(tabVentaLayout);
        tabVentaLayout.setHorizontalGroup(
            tabVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabVentaLayout.createSequentialGroup()
                .addComponent(lblVentas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        tabVentaLayout.setVerticalGroup(
            tabVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblVentas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, Short.MAX_VALUE)
        );

        tabGastos.setBackground(new java.awt.Color(204, 255, 204));
        tabGastos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tabGastos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabGastosMouseClicked(evt);
            }
        });

        lblGastos.setFont(new java.awt.Font("Lato", 1, 18)); // NOI18N
        lblGastos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGastos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cash_icon-icons.com_51090.png"))); // NOI18N
        lblGastos.setText("Gastos");
        lblGastos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblGastos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblGastosMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout tabGastosLayout = new javax.swing.GroupLayout(tabGastos);
        tabGastos.setLayout(tabGastosLayout);
        tabGastosLayout.setHorizontalGroup(
            tabGastosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabGastosLayout.createSequentialGroup()
                .addComponent(lblGastos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        tabGastosLayout.setVerticalGroup(
            tabGastosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblGastos, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("SALES SYSTEM");

        jSeparator1.setForeground(new java.awt.Color(51, 51, 51));

        tabUsuarios.setBackground(new java.awt.Color(204, 255, 204));

        lblusuarios.setFont(new java.awt.Font("Lato", 1, 18)); // NOI18N
        lblusuarios.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblusuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/find_search_card_user_16713.png"))); // NOI18N
        lblusuarios.setText("Usuarios");
        lblusuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblusuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblusuariosMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout tabUsuariosLayout = new javax.swing.GroupLayout(tabUsuarios);
        tabUsuarios.setLayout(tabUsuariosLayout);
        tabUsuariosLayout.setHorizontalGroup(
            tabUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblusuarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        tabUsuariosLayout.setVerticalGroup(
            tabUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabUsuariosLayout.createSequentialGroup()
                .addComponent(lblusuarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(3, 3, 3))
        );

        tabCliente1.setBackground(new java.awt.Color(204, 255, 204));
        tabCliente1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabCliente1MouseClicked(evt);
            }
        });

        lblClientes.setFont(new java.awt.Font("Lato", 1, 18)); // NOI18N
        lblClientes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/User-80_icon-icons.com_57249.png"))); // NOI18N
        lblClientes.setText("Clientes");
        lblClientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblClientesMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout tabCliente1Layout = new javax.swing.GroupLayout(tabCliente1);
        tabCliente1.setLayout(tabCliente1Layout);
        tabCliente1Layout.setHorizontalGroup(
            tabCliente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        tabCliente1Layout.setVerticalGroup(
            tabCliente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblClientes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        tabInventario.setBackground(new java.awt.Color(204, 255, 204));
        tabInventario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tabInventario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabInventarioMouseClicked(evt);
            }
        });

        lblInventarios.setFont(new java.awt.Font("Lato", 1, 18)); // NOI18N
        lblInventarios.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInventarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/1486504352-checklist-clipboard-inventory-list-report-tasks-todo_81326.png"))); // NOI18N
        lblInventarios.setText("Inventarios");
        lblInventarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblInventarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblInventariosMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout tabInventarioLayout = new javax.swing.GroupLayout(tabInventario);
        tabInventario.setLayout(tabInventarioLayout);
        tabInventarioLayout.setHorizontalGroup(
            tabInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabInventarioLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblInventarios, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        tabInventarioLayout.setVerticalGroup(
            tabInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblInventarios, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        tabProductos.setBackground(new java.awt.Color(204, 255, 204));
        tabProductos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lblProductos.setFont(new java.awt.Font("Lato", 1, 18)); // NOI18N
        lblProductos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/1486503758-bag-cart-goods-items-shopping_81288.png"))); // NOI18N
        lblProductos.setText("Productos");
        lblProductos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblProductosMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout tabProductosLayout = new javax.swing.GroupLayout(tabProductos);
        tabProductos.setLayout(tabProductosLayout);
        tabProductosLayout.setHorizontalGroup(
            tabProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabProductosLayout.createSequentialGroup()
                .addGap(0, 25, Short.MAX_VALUE)
                .addComponent(lblProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        tabProductosLayout.setVerticalGroup(
            tabProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblProductos, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        tabBoleta.setBackground(new java.awt.Color(204, 255, 204));
        tabBoleta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tabBoleta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabBoletaMouseClicked(evt);
            }
        });

        lblBoleta.setFont(new java.awt.Font("Lato", 1, 18)); // NOI18N
        lblBoleta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBoleta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cuenta.png"))); // NOI18N
        lblBoleta.setText("  Boletas");
        lblBoleta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblBoleta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBoletaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout tabBoletaLayout = new javax.swing.GroupLayout(tabBoleta);
        tabBoleta.setLayout(tabBoletaLayout);
        tabBoletaLayout.setHorizontalGroup(
            tabBoletaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabBoletaLayout.createSequentialGroup()
                .addComponent(lblBoleta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        tabBoletaLayout.setVerticalGroup(
            tabBoletaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblBoleta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
        );

        txtUsu.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        txtUsu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        txtCerrarSesion.setBackground(new java.awt.Color(204, 204, 204));
        txtCerrarSesion.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtCerrarSesion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtCerrarSesion.setText("Cerrar Sesión");
        txtCerrarSesion.setOpaque(true);
        txtCerrarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtCerrarSesionMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabhome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tabPersonal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tabCaja, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tabVenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tabGastos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tabUsuarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tabCliente1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tabInventario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tabProductos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tabBoleta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtUsu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel6)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(txtCerrarSesion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(tabhome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtCerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tabPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabCaja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tabVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tabCliente1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tabUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tabGastos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tabInventario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tabProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabBoleta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(102, 102, 102))
        );

        jPanel2.setBackground(new java.awt.Color(255, 204, 204));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        panelhome.setBackground(new java.awt.Color(255, 255, 255));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo.jpg"))); // NOI18N
        jLabel20.setMaximumSize(new java.awt.Dimension(1258, 1204));
        jLabel20.setMinimumSize(new java.awt.Dimension(1258, 1204));
        jLabel20.setPreferredSize(new java.awt.Dimension(1258, 1204));

        javax.swing.GroupLayout panelhomeLayout = new javax.swing.GroupLayout(panelhome);
        panelhome.setLayout(panelhomeLayout);
        panelhomeLayout.setHorizontalGroup(
            panelhomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, 2149, Short.MAX_VALUE)
        );
        panelhomeLayout.setVerticalGroup(
            panelhomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelhomeLayout.createSequentialGroup()
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 745, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 68, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2159, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addComponent(panelhome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 842, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelhome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tabCajaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabCajaMouseClicked
      try{ FrmCaja cajaventana = new FrmCaja();
                cajaventana.setVisible(true);
                
         tabCaja.setBackground(Color.WHITE);
         tabhome.setBackground(new Color(204,204,255));
         tabPersonal.setBackground(new Color(204,204,255));
         tabVenta.setBackground(new Color(204,204,255));
         tabCliente1.setBackground(new Color(204,204,255));
         tabUsuarios.setBackground(new Color(204,204,255));
         tabGastos.setBackground(new Color(204,204,255));
         tabInventario.setBackground(new Color(204,204,255));
         tabProductos.setBackground(new Color(204,204,255));
         tabBoleta.setBackground(new Color(204,204,255));}catch(Exception ex){
           System.out.println("Formulario : "+ex.getMessage());
      }
    }//GEN-LAST:event_tabCajaMouseClicked

    private void lblPersonalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPersonalMouseClicked
      try{      FrmPersonal personalventana = new FrmPersonal();
                personalventana.setVisible(true);

       
        //cambiar color al presionar
         tabPersonal.setBackground(Color.WHITE);
        
        tabhome.setBackground(new Color(204,255,204));
         tabCaja.setBackground(new Color(204,255,204));
         tabVenta.setBackground(new Color(204,255,204));
         tabCliente1.setBackground(new Color(204,255,204));
         tabUsuarios.setBackground(new Color(204,255,204));
         tabGastos.setBackground(new Color(204,255,204));
         tabInventario.setBackground(new Color(204,255,204));
         tabProductos.setBackground(new Color(204,255,204));
         tabBoleta.setBackground(new Color(204,255,204));}catch(Exception ex){
           System.out.println("Formulario : "+ex.getMessage());
      }
    }//GEN-LAST:event_lblPersonalMouseClicked

    private void lblCajaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCajaMouseClicked
       try{ FrmCaja cajaventana = new FrmCaja();
                cajaventana.setVisible(true);
                
         tabCaja.setBackground(Color.WHITE);
        
        tabhome.setBackground(new Color(204,255,204));
         tabPersonal.setBackground(new Color(204,255,204));
         tabVenta.setBackground(new Color(204,255,204));
         tabCliente1.setBackground(new Color(204,255,204));
         tabUsuarios.setBackground(new Color(204,255,204));
         tabGastos.setBackground(new Color(204,255,204));
         tabInventario.setBackground(new Color(204,255,204));
         tabProductos.setBackground(new Color(204,255,204));
         tabBoleta.setBackground(new Color(204,255,204));}catch(Exception ex){
           System.out.println("Formulario : "+ex.getMessage());
      }
    }//GEN-LAST:event_lblCajaMouseClicked

    private void lblVentasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVentasMouseClicked
       try{     FrmDetalle_Venta VentasClienteventana = new FrmDetalle_Venta();
                VentasClienteventana.setVisible(true);
        
        
         tabVenta.setBackground(Color.WHITE);
        
        tabhome.setBackground(new Color(204,255,204));
         tabPersonal.setBackground(new Color(204,255,204));
         tabCaja.setBackground(new Color(204,255,204));
         tabCliente1.setBackground(new Color(204,255,204));
         tabUsuarios.setBackground(new Color(204,255,204));
         tabGastos.setBackground(new Color(204,255,204));
         tabInventario.setBackground(new Color(204,255,204));
         tabProductos.setBackground(new Color(204,255,204));
         tabBoleta.setBackground(new Color(204,255,204));}catch(Exception ex){
           System.out.println("Formulario : "+ex.getMessage());
      }
    }//GEN-LAST:event_lblVentasMouseClicked

    private void lblClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblClientesMouseClicked
       try{     FrmClientes clientesventana = new FrmClientes();
                clientesventana.setVisible(true);
        
        tabCliente1.setBackground(Color.WHITE);
        
        tabhome.setBackground(new Color(204,255,204));
         tabPersonal.setBackground(new Color(204,255,204));
         tabCaja.setBackground(new Color(204,255,204));
         tabVenta.setBackground(new Color(204,255,204));
         tabUsuarios.setBackground(new Color(204,255,204));
         tabGastos.setBackground(new Color(204,255,204));
         tabInventario.setBackground(new Color(204,255,204));
         tabProductos.setBackground(new Color(204,255,204));
         tabBoleta.setBackground(new Color(204,255,204));}catch(Exception ex){
           System.out.println("Formulario : "+ex.getMessage());
      }
    }//GEN-LAST:event_lblClientesMouseClicked

    private void lblusuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblusuariosMouseClicked
      try{  FrmUsuario usuarioventana = new FrmUsuario();
                usuarioventana.setVisible(true);
                
       
         //Cambiar de color al hacer clic
         tabUsuarios.setBackground(Color.WHITE);
        
        tabhome.setBackground(new Color(204,255,204));
         tabPersonal.setBackground(new Color(204,255,204));
         tabCaja.setBackground(new Color(204,255,204));
         tabVenta.setBackground(new Color(204,255,204));
         tabCliente1.setBackground(new Color(204,255,204));
         tabGastos.setBackground(new Color(204,255,204));
         tabInventario.setBackground(new Color(204,255,204));
         tabProductos.setBackground(new Color(204,255,204));
         tabBoleta.setBackground(new Color(204,255,204));}catch(Exception ex){
           System.out.println("Formulario : "+ex.getMessage());
      }
    }//GEN-LAST:event_lblusuariosMouseClicked

    private void lblGastosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGastosMouseClicked
          try{  FrmGastos gastosventana = new FrmGastos();
                gastosventana.setVisible(true);

        
       
         //Cambiar de color al hacer clic
         tabGastos.setBackground(Color.WHITE);
        
        tabhome.setBackground(new Color(204,255,204));
         tabPersonal.setBackground(new Color(204,255,204));
         tabCaja.setBackground(new Color(204,255,204));
         tabVenta.setBackground(new Color(204,255,204));
         tabCliente1.setBackground(new Color(204,255,204));
         tabUsuarios.setBackground(new Color(204,255,204));
         tabInventario.setBackground(new Color(204,255,204));
         tabProductos.setBackground(new Color(204,255,204));
         tabBoleta.setBackground(new Color(204,255,204));}catch(Exception ex){
           System.out.println("Formulario : "+ex.getMessage());
      }
    }//GEN-LAST:event_lblGastosMouseClicked

    private void lblInventariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblInventariosMouseClicked
     try{ FrmInventarios inventarioventana = new FrmInventarios();
                inventarioventana.setVisible(true);
      
                
         //Cambiar de color al hacer clic
         tabInventario.setBackground(Color.WHITE);
        
        tabhome.setBackground(new Color(204,255,204));
         tabPersonal.setBackground(new Color(204,255,204));
         tabCaja.setBackground(new Color(204,255,204));
         tabVenta.setBackground(new Color(204,255,204));
         tabCliente1.setBackground(new Color(204,255,204));
         tabGastos.setBackground(new Color(204,255,204));
         tabUsuarios.setBackground(new Color(204,255,204));
         tabProductos.setBackground(new Color(204,255,204));
         tabBoleta.setBackground(new Color(204,255,204));}catch(Exception ex){
           System.out.println("Formulario : "+ex.getMessage());
      }
    }//GEN-LAST:event_lblInventariosMouseClicked

    private void lblProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblProductosMouseClicked
   try{FrmProductos productoventana = new FrmProductos();
   productoventana.setVisible(true);
    
   
        
         //Cambiar de color al hacer clic
         tabProductos.setBackground(Color.WHITE);
        
        tabhome.setBackground(new Color(204,255,204));
         tabPersonal.setBackground(new Color(204,255,204));
         tabCaja.setBackground(new Color(204,255,204));
         tabVenta.setBackground(new Color(204,255,204));
         tabCliente1.setBackground(new Color(204,255,204));
         tabGastos.setBackground(new Color(204,255,204));
         tabInventario.setBackground(new Color(204,255,204));
         tabUsuarios.setBackground(new Color(204,255,204));
         tabBoleta.setBackground(new Color(204,255,204));
         }catch(Exception ex){
           System.out.println("Formulario : "+ex.getMessage());
      }
    }//GEN-LAST:event_lblProductosMouseClicked

    private void lblBoletaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBoletaMouseClicked
       try{ FrmVentas boletaventana = new FrmVentas();
                boletaventana.setVisible(true);
        
       
         //Cambiar de color al hacer clic
          tabBoleta.setBackground(Color.WHITE);
        
        tabhome.setBackground(new Color(204,255,204));
         tabPersonal.setBackground(new Color(204,255,204));
         tabCaja.setBackground(new Color(204,255,204));
         tabVenta.setBackground(new Color(204,255,204));
         tabCliente1.setBackground(new Color(204,255,204));
         tabGastos.setBackground(new Color(204,255,204));
         tabInventario.setBackground(new Color(204,255,204));
         tabProductos.setBackground(new Color(204,255,204));
         tabUsuarios.setBackground(new Color(204,255,204));
         }catch(Exception ex){
           System.out.println("Formulario : "+ex.getMessage());
      }
    }//GEN-LAST:event_lblBoletaMouseClicked

    
    private void lblHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHomeMouseClicked
      
     try{
  tabhome.setBackground(Color.WHITE);
        
        tabVenta.setBackground(new Color(204,255,204));
         tabPersonal.setBackground(new Color(204,255,204));
         tabCaja.setBackground(new Color(204,255,204));
         tabCliente1.setBackground(new Color(204,255,204));
         tabUsuarios.setBackground(new Color(204,255,204));
         tabGastos.setBackground(new Color(204,255,204));
         tabInventario.setBackground(new Color(204,255,204));
         tabProductos.setBackground(new Color(204,255,204));
         tabBoleta.setBackground(new Color(204,255,204));}catch(Exception ex){
           System.out.println("Formulario : "+ex.getMessage());
      }

    }//GEN-LAST:event_lblHomeMouseClicked

    private void tabCliente1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabCliente1MouseClicked
        
        try{
  tabCliente1.setBackground(Color.WHITE);
        
        tabhome.setBackground(new Color(204,255,204));
         tabPersonal.setBackground(new Color(204,255,204));
         tabCaja.setBackground(new Color(204,255,204));
         tabVenta.setBackground(new Color(204,255,204));
         tabUsuarios.setBackground(new Color(204,255,204));
         tabGastos.setBackground(new Color(204,255,204));
         tabInventario.setBackground(new Color(204,255,204));
         tabProductos.setBackground(new Color(204,255,204));
         tabBoleta.setBackground(new Color(204,255,204));}catch(Exception ex){
           System.out.println("Formulario : "+ex.getMessage());
      }
    }//GEN-LAST:event_tabCliente1MouseClicked

    private void tabGastosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabGastosMouseClicked
        //listarGastos();
    }//GEN-LAST:event_tabGastosMouseClicked

    private void tabBoletaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabBoletaMouseClicked
       try{ FrmVentas boletaventana = new FrmVentas();
                boletaventana.setVisible(true);
        
       
         //Cambiar de color al hacer clic
        
  tabBoleta.setBackground(Color.WHITE);
        
        tabhome.setBackground(new Color(204,255,204));
         tabPersonal.setBackground(new Color(204,255,204));
         tabCaja.setBackground(new Color(204,255,204));
         tabCliente1.setBackground(new Color(204,255,204));
         tabUsuarios.setBackground(new Color(204,255,204));
         tabGastos.setBackground(new Color(204,255,204));
         tabInventario.setBackground(new Color(204,255,204));
         tabProductos.setBackground(new Color(204,255,204));
         tabVenta.setBackground(new Color(204,255,204));}catch(Exception ex){
           System.out.println("Formulario : "+ex.getMessage());
      }
    }//GEN-LAST:event_tabBoletaMouseClicked

    private void tabInventarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabInventarioMouseClicked
      try{  FrmInventarios inventarioventana = new FrmInventarios();
                inventarioventana.setVisible(true);
      
                
         //Cambiar de color al hacer clic
        
  tabInventario.setBackground(Color.WHITE);
        
        tabhome.setBackground(new Color(204,255,204));
         tabPersonal.setBackground(new Color(204,255,204));
         tabCaja.setBackground(new Color(204,255,204));
         tabCliente1.setBackground(new Color(204,255,204));
         tabUsuarios.setBackground(new Color(204,255,204));
         tabGastos.setBackground(new Color(204,255,204));
         tabVenta.setBackground(new Color(204,255,204));
         tabProductos.setBackground(new Color(204,255,204));
         tabBoleta.setBackground(new Color(204,255,204));}catch(Exception ex){
           System.out.println("Formulario : "+ex.getMessage());
      }
    }//GEN-LAST:event_tabInventarioMouseClicked

    private void tabhomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabhomeMouseClicked
    try{   
  tabhome.setBackground(Color.WHITE);
        
        tabVenta.setBackground(new Color(204,255,204));
         tabPersonal.setBackground(new Color(204,255,204));
         tabCaja.setBackground(new Color(204,255,204));
         tabCliente1.setBackground(new Color(204,255,204));
         tabUsuarios.setBackground(new Color(204,255,204));
         tabGastos.setBackground(new Color(204,255,204));
         tabInventario.setBackground(new Color(204,255,204));
         tabProductos.setBackground(new Color(204,255,204));
         tabBoleta.setBackground(new Color(204,255,204));}catch(Exception ex){
           System.out.println("Formulario : "+ex.getMessage());
      }
    }//GEN-LAST:event_tabhomeMouseClicked

    private void txtCerrarSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCerrarSesionMouseClicked
       FrmLogin lg = new FrmLogin();
       lg.setVisible(true);
       lg.setLocationRelativeTo(null);
      this.dispose();
    }//GEN-LAST:event_txtCerrarSesionMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblBoleta;
    private javax.swing.JLabel lblCaja;
    private javax.swing.JLabel lblClientes;
    private javax.swing.JLabel lblGastos;
    private javax.swing.JLabel lblHome;
    private javax.swing.JLabel lblInventarios;
    private javax.swing.JLabel lblPersonal;
    private javax.swing.JLabel lblProductos;
    private javax.swing.JLabel lblVentas;
    private javax.swing.JLabel lblusuarios;
    private javax.swing.JPanel panelhome;
    private javax.swing.JPanel tabBoleta;
    private javax.swing.JPanel tabCaja;
    private javax.swing.JPanel tabCliente1;
    private javax.swing.JPanel tabGastos;
    private javax.swing.JPanel tabInventario;
    private javax.swing.JPanel tabPersonal;
    private javax.swing.JPanel tabProductos;
    private javax.swing.JPanel tabUsuarios;
    private javax.swing.JPanel tabVenta;
    private javax.swing.JPanel tabhome;
    private javax.swing.JLabel txtCerrarSesion;
    private javax.swing.JLabel txtUsu;
    // End of variables declaration//GEN-END:variables
}
