/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CapaNegocios;

import CapaDatos.PersonalDAO;
import CapaEntidad.ConstructorPersonal;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Gian
 */
public class FrmPersonal extends javax.swing.JFrame {
PersonalDAO oPersonalDAO = new PersonalDAO();
     void limpiarPersonal(){
   
        txtNombrePersonal.setText("");
        txtDniPersonal.setText("");
        txtTlfPersonal.setText("");
        txtPagaPersonal.setText("");
        
    }
    void activarCajasPersonal(boolean v){
        
        txtNombrePersonal.setEnabled(v);
        txtDniPersonal.setEnabled(v);
        txtTlfPersonal.setEnabled(v);
        txtPagaPersonal.setEnabled(v);
       
        
        
    }
    void activarBotonesPersonal(boolean botonAgregar,boolean botonBuscar,boolean botonActualizar,boolean botonEliminar){
        btnAgregarPersonal.setEnabled(botonAgregar);
        btnBuscarPersonal.setEnabled(botonBuscar);
        btnModificarPersonal.setEnabled(botonActualizar);
        btnEliminarPersonal.setEnabled(botonEliminar);   
    }

      void listarPersonal(){
          DefaultTableModel modelo=new DefaultTableModel();
        String [] titulos= {"IDPERSONAL","NOMBRE COMPLETO","NUM DOCUMENTO","TELEFONO","PAGA"};
        modelo.setColumnIdentifiers(titulos);
        ArrayList<ConstructorPersonal> lista= oPersonalDAO.listarPersonal();
        for(ConstructorPersonal ocomDatos:lista){
            Object data[]={ocomDatos.getCodigo(),ocomDatos.getNombre(),ocomDatos.getDocum(),ocomDatos.getTelefono(),ocomDatos.getPaga()};
            modelo.addRow(data);
        }
        TblPersonal.setModel(modelo);
        personalizarTablaPersonal();   
    }
    private void personalizarTablaPersonal(){
        TblPersonal.getColumnModel().getColumn(0).setPreferredWidth(100);
        TblPersonal.getColumnModel().getColumn(1).setPreferredWidth(100);
        TblPersonal.getColumnModel().getColumn(2).setPreferredWidth(100);
        TblPersonal.getColumnModel().getColumn(3).setPreferredWidth(100);      
    } 
     void mensaje(String men){
        JOptionPane.showMessageDialog(this, men,"Aviso",1);
    }
     
     public int id_auto(){
         int id_max2 = 1;
       
        
        try{
            id_max2 = oPersonalDAO.auto_increm("SELECT MAX(IDPERSONAL) FROM PERSONAL;");
        }catch(Exception ex){
            System.out.println(ex.getMessage());
        }
        return id_max2;
        
    }
    public FrmPersonal() {
        initComponents();
          listarPersonal();
          this.setLocationRelativeTo(null);
        activarCajasPersonal(false); 
        activarBotonesPersonal(false,true,false,false);
          this.txtidpersona.setText(String.valueOf(id_auto()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        pnlBackground = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        PnldeTextos = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnBuscarPersonal = new javax.swing.JButton();
        txtidpersona = new javax.swing.JTextField();
        txtNombrePersonal = new javax.swing.JTextField();
        txtPagaPersonal = new javax.swing.JTextField();
        txtTlfPersonal = new javax.swing.JTextField();
        txtDniPersonal = new javax.swing.JTextField();
        pnlTabla = new javax.swing.JPanel();
        btnModificarPersonal = new javax.swing.JButton();
        btnEliminarPersonal = new javax.swing.JButton();
        btnAgregarPersonal = new javax.swing.JButton();
        btnNuevoPersonal = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TblPersonal = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Personal");
        setMinimumSize(new java.awt.Dimension(880, 580));
        setPreferredSize(new java.awt.Dimension(880, 580));
        setResizable(false);

        pnlBackground.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));

        jLabel1.setFont(new java.awt.Font("Javanese Text", 1, 32)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Personal");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/p.png"))); // NOI18N
        jLabel4.setText("jLabel4");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1001, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pnlBackground.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        PnldeTextos.setBackground(new java.awt.Color(255, 255, 255));
        PnldeTextos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Id Persona:");
        PnldeTextos.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 11, 64, -1));

        jLabel3.setText("Nombre Completo:");
        PnldeTextos.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 107, -1));

        jLabel5.setText("Paga:");
        PnldeTextos.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, 48, -1));

        jLabel6.setText("Telefono:");
        PnldeTextos.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, 64, -1));

        jLabel7.setText("Numero de documento:");
        PnldeTextos.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, 140, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-cambiar-usuario-masculino-80.png"))); // NOI18N
        PnldeTextos.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 20, 80, 110));

        btnBuscarPersonal.setBackground(new java.awt.Color(255, 255, 255));
        btnBuscarPersonal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-buscar-cliente-30.png"))); // NOI18N
        btnBuscarPersonal.setText("Buscar");
        btnBuscarPersonal.setBorder(null);
        btnBuscarPersonal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscarPersonal.setFocusPainted(false);
        btnBuscarPersonal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarPersonalActionPerformed(evt);
            }
        });
        PnldeTextos.add(btnBuscarPersonal, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 90, -1));

        txtidpersona.setEnabled(false);
        PnldeTextos.add(txtidpersona, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 31, 55, -1));

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, txtDniPersonal, org.jdesktop.beansbinding.ObjectProperty.create(), txtNombrePersonal, org.jdesktop.beansbinding.BeanProperty.create("nextFocusableComponent"));
        bindingGroup.addBinding(binding);

        txtNombrePersonal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombrePersonalKeyTyped(evt);
            }
        });
        PnldeTextos.add(txtNombrePersonal, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 148, -1));

        txtPagaPersonal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPagaPersonalKeyTyped(evt);
            }
        });
        PnldeTextos.add(txtPagaPersonal, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 90, 150, -1));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, txtPagaPersonal, org.jdesktop.beansbinding.ObjectProperty.create(), txtTlfPersonal, org.jdesktop.beansbinding.BeanProperty.create("nextFocusableComponent"));
        bindingGroup.addBinding(binding);

        txtTlfPersonal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTlfPersonalKeyTyped(evt);
            }
        });
        PnldeTextos.add(txtTlfPersonal, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 60, 148, -1));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, txtTlfPersonal, org.jdesktop.beansbinding.ObjectProperty.create(), txtDniPersonal, org.jdesktop.beansbinding.BeanProperty.create("nextFocusableComponent"));
        bindingGroup.addBinding(binding);

        txtDniPersonal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDniPersonalKeyTyped(evt);
            }
        });
        PnldeTextos.add(txtDniPersonal, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 30, 148, -1));

        pnlTabla.setBackground(new java.awt.Color(255, 255, 255));

        btnModificarPersonal.setBackground(new java.awt.Color(255, 255, 255));
        btnModificarPersonal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-editar-usuario-masculino-30.png"))); // NOI18N
        btnModificarPersonal.setText("Modifcar");
        btnModificarPersonal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnModificarPersonal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarPersonalActionPerformed(evt);
            }
        });

        btnEliminarPersonal.setBackground(new java.awt.Color(255, 255, 255));
        btnEliminarPersonal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-retire-hombre-usuario-30.png"))); // NOI18N
        btnEliminarPersonal.setText("Eliminar");
        btnEliminarPersonal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminarPersonal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarPersonalActionPerformed(evt);
            }
        });

        btnAgregarPersonal.setBackground(new java.awt.Color(255, 255, 255));
        btnAgregarPersonal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-añadir-usuario-masculino-30.png"))); // NOI18N
        btnAgregarPersonal.setText("Agregar");
        btnAgregarPersonal.setBorder(null);
        btnAgregarPersonal.setBorderPainted(false);
        btnAgregarPersonal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregarPersonal.setFocusPainted(false);
        btnAgregarPersonal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarPersonalActionPerformed(evt);
            }
        });

        btnNuevoPersonal.setBackground(new java.awt.Color(255, 255, 255));
        btnNuevoPersonal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/editar.png"))); // NOI18N
        btnNuevoPersonal.setText("Nuevo");
        btnNuevoPersonal.setBorder(null);
        btnNuevoPersonal.setBorderPainted(false);
        btnNuevoPersonal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNuevoPersonal.setFocusPainted(false);
        btnNuevoPersonal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoPersonalActionPerformed(evt);
            }
        });

        TblPersonal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(TblPersonal);

        javax.swing.GroupLayout pnlTablaLayout = new javax.swing.GroupLayout(pnlTabla);
        pnlTabla.setLayout(pnlTablaLayout);
        pnlTablaLayout.setHorizontalGroup(
            pnlTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTablaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 654, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnNuevoPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregarPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnModificarPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminarPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlTablaLayout.setVerticalGroup(
            pnlTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTablaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlTablaLayout.createSequentialGroup()
                        .addComponent(btnNuevoPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAgregarPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnModificarPersonal)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminarPersonal)))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlBackground, javax.swing.GroupLayout.DEFAULT_SIZE, 1269, Short.MAX_VALUE)
                    .addComponent(PnldeTextos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlTabla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PnldeTextos, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlTabla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnModificarPersonalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarPersonalActionPerformed
        try {
            String m;
            m = oPersonalDAO.actualizarPersonal(new ConstructorPersonal(Integer.parseInt(txtidpersona.getText()),txtNombrePersonal.getText(),Integer.parseInt(txtDniPersonal.getText()),Integer.parseInt(txtTlfPersonal.getText()),Float.parseFloat(txtPagaPersonal.getText())));
            mensaje(m);
            listarPersonal();
            limpiarPersonal();
            this.txtidpersona.setText(String.valueOf(id_auto()));
            activarBotonesPersonal(false,true,false,false);
            activarCajasPersonal(false);
            btnNuevoPersonal.setText("Nuevo");
        } catch (Exception ex) {
            System.out.println("Modificar : "+ex.getMessage());
        }
    }//GEN-LAST:event_btnModificarPersonalActionPerformed

    private void btnEliminarPersonalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarPersonalActionPerformed
      try{  String m=oPersonalDAO.eliminarPersonal(Integer.parseInt(txtidpersona.getText()));
        mensaje(m);
        listarPersonal();
        limpiarPersonal();
        this.txtidpersona.setText(String.valueOf(id_auto()));
        activarBotonesPersonal(false,true,false,false);
        activarCajasPersonal(false);
        }catch(Exception ex){
           System.out.println("Eliminar : "+ex.getMessage());
      }
    }//GEN-LAST:event_btnEliminarPersonalActionPerformed

    private void btnAgregarPersonalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarPersonalActionPerformed
        try {
            String m;
            m = oPersonalDAO.agregarPersonal(new ConstructorPersonal(Integer.parseInt(txtidpersona.getText()),txtNombrePersonal.getText(),Integer.parseInt(txtDniPersonal.getText()),Integer.parseInt(txtTlfPersonal.getText()),Float.parseFloat(txtPagaPersonal.getText())));
            mensaje(m);
            listarPersonal();
            limpiarPersonal();
            this.txtidpersona.setText(String.valueOf(id_auto()));
            activarBotonesPersonal(false,true,false,false);
            activarCajasPersonal(false);
            btnNuevoPersonal.setText("Nuevo");
        } catch (Exception ex) {
            System.out.println("Agregar : "+ex.getMessage());
        }
    }//GEN-LAST:event_btnAgregarPersonalActionPerformed

    private void btnNuevoPersonalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoPersonalActionPerformed
      try{ 
          if(btnNuevoPersonal.getText().equalsIgnoreCase("Nuevo")){
            limpiarPersonal();
            activarBotonesPersonal(true,false,false,false);
            activarCajasPersonal(true);
            btnNuevoPersonal.setText("Cancelar");
          this.txtidpersona.setText(String.valueOf(id_auto()));
        }else {
            limpiarPersonal();
            activarBotonesPersonal(false,true,false,false);
            activarCajasPersonal(false);
            btnNuevoPersonal.setText("Nuevo");
            
          }}catch(Exception ex){
           System.out.println("Nuevo : "+ex.getMessage());
      }
      
    }//GEN-LAST:event_btnNuevoPersonalActionPerformed

    private void btnBuscarPersonalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarPersonalActionPerformed
      try{  
          ConstructorPersonal oPersonal;
        int dato=Integer.parseInt(JOptionPane.showInputDialog("Codigo a buscar "));
        oPersonal=oPersonalDAO.buscarPersonal(dato);
        if(oPersonal==null){
            mensaje("CODIGO NO EXISTE");
            limpiarPersonal();
            activarBotonesPersonal(false,false,false,false);
            activarCajasPersonal(false);
        }else{
            txtidpersona.setText(""+oPersonal.getCodigo());
            txtNombrePersonal.setText(oPersonal.getNombre());
            txtDniPersonal.setText(""+oPersonal.getDocum());
            txtTlfPersonal.setText(""+oPersonal.getTelefono());
            txtPagaPersonal.setText(""+oPersonal.getPaga());

            activarBotonesPersonal(false,false,true,true);
            activarCajasPersonal(true);
        } }catch(Exception ex){
           System.out.println("Buscar : "+ex.getMessage());
      }
        
    }//GEN-LAST:event_btnBuscarPersonalActionPerformed

    private void txtTlfPersonalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTlfPersonalKeyTyped
     char validar= evt.getKeyChar();
      if(Character.isLetter(validar)){
          getToolkit().beep();
          evt.consume();
          JOptionPane.showMessageDialog((rootPane), "Ingresar solo Números");
      }
       if(txtTlfPersonal.getText().length()>=12)
        {
             getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog((rootPane), "Solo se permite 12 digitos");
        }
    }//GEN-LAST:event_txtTlfPersonalKeyTyped

    private void txtPagaPersonalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPagaPersonalKeyTyped
       char validar= evt.getKeyChar();
      if(Character.isLetter(validar)){
          getToolkit().beep();
          evt.consume();
          JOptionPane.showMessageDialog((rootPane), "Ingresar solo Números");
      }
       if(txtPagaPersonal.getText().length()>=7)
        {
             getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog((rootPane), "Solo se permite 7 digitos");
        }
    }//GEN-LAST:event_txtPagaPersonalKeyTyped

    private void txtDniPersonalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDniPersonalKeyTyped
       char validar= evt.getKeyChar();
      if(Character.isLetter(validar)){
          getToolkit().beep();
          evt.consume();
          JOptionPane.showMessageDialog((rootPane), "Ingresar solo Números");
      }
       if(txtDniPersonal.getText().length()>=8)
        {
             getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog((rootPane), "Solo se permite 8 caracteres");
        }
    }//GEN-LAST:event_txtDniPersonalKeyTyped

    private void txtNombrePersonalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombrePersonalKeyTyped
        char validar= evt.getKeyChar();
      if(Character.isDigit(validar)){
          getToolkit().beep();
          evt.consume();
          JOptionPane.showMessageDialog((rootPane), "Ingresar solo letras");
      }
       if(txtNombrePersonal.getText().length()>=60)
        {
             getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog((rootPane), "Solo se permite 60 caracteres");
        }
      
    }//GEN-LAST:event_txtNombrePersonalKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPersonal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPersonal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPersonal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPersonal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPersonal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PnldeTextos;
    private javax.swing.JTable TblPersonal;
    private javax.swing.JButton btnAgregarPersonal;
    private javax.swing.JButton btnBuscarPersonal;
    private javax.swing.JButton btnEliminarPersonal;
    private javax.swing.JButton btnModificarPersonal;
    private javax.swing.JButton btnNuevoPersonal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel pnlBackground;
    private javax.swing.JPanel pnlTabla;
    private javax.swing.JTextField txtDniPersonal;
    private javax.swing.JTextField txtNombrePersonal;
    private javax.swing.JTextField txtPagaPersonal;
    private javax.swing.JTextField txtTlfPersonal;
    private javax.swing.JTextField txtidpersona;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
